language: python
python: 2.7
env:
  - TOX_ENV=py27
  - TOX_ENV=flake8
install:
  - pip install tox coveralls
script:
  - tox -e $TOX_ENV
  - coverage run -m coverage run -m xunit xunit.test.tests
after_success:
  - coveralls
